# -*- mode: ruby -*-
# vi: set ft=ruby :
#
home_vb = ENV['VBOX_storage']
ENV['GIT_DISCOVERY_ACROSS_FILESYSTEM'] = '1'
MACHINES = {
  :arch_linux_vagrant => {
        :box_name => "generic/arch",
        :ip_addr => '192.168.56.3',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 250, # Megabytes
			:port => 2
                }

	}
		
  },
}

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-env"

  config.env.enable # enable the plugin
  #config.vm.box = ENV['BOX_NAME']
  config.vm.box= ENV['GIT_DISCOVERY_ACROSS_FILESYSTEM']
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = "arch-vagrant"
      box.vm.box_version = "3.5.4"
      box.ssh.username = 'vagrant'
      #box.ssh.password = 'vagrant'
      box.ssh.keys_only = true
      box.ssh.insert_key = true
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.synced_folder ".", "/home/vagrant/share", disabled: false, type: 'virtualbox',:mount_options => ["dmode=777", "fmode=666"],create: true
      box.vbguest.auto_update = false
      #box.vm.synced_folder "/tmp", "/tmp/src" 
      #box.vm.provider "virtualbox" do |vb|
      #vb.memory = "2048"
      #vb.cpu = "3"
    #end

    box.vm.provider :virtualbox do |vb|
                  #vb.customize ["modifyvm", :id, "--memory", "1024"]
                  vb.memory = "2048"
                  vb.cpus = "3"
                  needsController = false

                  boxconfig[:disks].each do |dname, dconf|
                          unless File.exist?(dconf[:dfile])
                                vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

                  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
    end
  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              pacman -Syu base-devel cmake gcc git net-tools autoconf vim mc nnn ncurses
	  SHELL
  config.vm.provision "shell", inline: "export MY_VAR='value'"
      end
  end
end

